# -*- coding: utf-8 -*-
"""Restaurantminiproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmnPm0s1SgqAO16aEZpmVtA78-c-m6Tv
"""

menu = {
    'Pasta':80,
    'Pizza':100,
    'Garlic Bread':90,
    'Coffee Latte':120,
    'Mojito':80,
}

print("Welcome to Little Nook Cafe")
print("Our menu has:")
print("Pasta:Rs80\nPizza:Rs100\nGarlic Bread:Rs90\nCoffee Latte:Rs120\nMojito:Rs80")

order_total= 0

item_1 = input("Enter the 1st item you want to order ")
if item_1 in menu:
     order_total += menu[item_1]
     print(f"Your item {item_1} has been added to your order")

else:
     print(f"This item {item_1} is not yet added in our menu")

print(f"Your order total is {order_total}")

another_order = input("Do you want to order another item? (Yes/No)")
if another_order == "Yes":
      item_2 = input("Enter the 2nd item you want to order ")
      if item_2 in menu:
         order_total+= menu[item_2]
         print(f"Your item {item_2} has been added to your order")
      else:
         print(f"This item {item_2} is not yet added in our menu")
print(f"Your order total is {order_total}")

another_order = input("Do you want to order another item? (Yes/No)")
if another_order == "Yes":
      item_3 = input("Enter the 3rd item you want to order ")
      if item_3 in menu:
         order_total+= menu[item_3]
         print(f"Your item {item_3} has been added to your order")
else:
     print(f"This item {item_3} is not yet added in our menu")
print(f"Your order total is {order_total}")

another_order = input("Do you want to order another item? (Yes/No)")
if another_order == "Yes":
      item_4 = input("Enter the 4th item you want to order ")
      if item_4 in menu:
         order_total+= menu[item_4]
         print(f"Your item {item_4} has been added to your order")
      else:
         print(f"This item {item_4} is not yet added in our menu")
print(f"Your order total is {order_total}")

another_order = input("Do you want to order another item? (Yes/No)")
if another_order == "Yes":
      item_5 = input("Enter the 5th item you want to order ")
      if item_5 in menu:
         order_total+= menu[item_5]
         print(f"Your item {item_5} has been added to your order")
      else:
         print(f"This item {item_5} is not yet added in our menu")
print(f"Your order total is {order_total}")

print("Thank you for your order, do come back again!")